from collections import defaultdict

group_dict = {"female": ["demo"],
              "map_testritscore": ["map"],
              "map_testpercentile": ["map"],
              "map_testdurationminutes": ["map"],
              "map_percentcorrect": ["map"],
              "map_start_date": ["map"],
              "map_start_hour": ["map"],
              "map_season": ["map"],
              'map_reading_testritscore': ["map"],
              'map_reading_testpercentile': ["map"],
              'map_reading_testdurationminutes': ["map"],
              'map_reading_percentcorrect': ["map"],
              'map_reading_start_date': ["map"],
              'map_reading_start_hour': ["map"],
              'map_max_score': ["map", "baseline"],
              "tripod_challenge_min": ["tripod","actionable"],
              "tripod_challenge_max": ["tripod","actionable"],
              "tripod_challenge_mean": ["tripod","actionable"],
              "tripod_challenge_std": ["tripod","actionable"],
              "tripod_classroom_management_min": ["tripod","actionable"],
              "tripod_classroom_management_max": ["tripod","actionable"],
              "tripod_classroom_management_mean": ["tripod","actionable"],
              "tripod_classroom_management_std": ["tripod","actionable"],
              "tripod_captivate_min": ["tripod","actionable"],
              "tripod_captivate_max": ["tripod","actionable"],
              "tripod_captivate_mean": ["tripod","actionable"],
              "tripod_captivate_std": ["tripod","actionable"],
              "tripod_care_min": ["tripod","actionable"],
              "tripod_care_max": ["tripod","actionable"],
              "tripod_care_mean": ["tripod","actionable"],
              "tripod_care_std": ["tripod","actionable"],
              "tripod_clarify_min": ["tripod","actionable"],
              "tripod_clarify_max": ["tripod","actionable"],
              "tripod_clarify_mean": ["tripod","actionable"],
              "tripod_clarify_std": ["tripod","actionable"],
              "tripod_consolidate_min": ["tripod","actionable"],
              "tripod_consolidate_max": ["tripod","actionable"],
              "tripod_consolidate_mean": ["tripod","actionable"],
              "tripod_consolidate_std": ["tripod","actionable"],
              "tripod_confer_min": ["tripod","actionable"],
              "tripod_confer_max": ["tripod","actionable"],
              "tripod_confer_mean": ["tripod","actionable"],
              "tripod_confer_std": ["tripod","actionable"],
              "tripod_cs_min": ["tripod","actionable"],
              "tripod_cs_max": ["tripod","actionable"],
              "tripod_cs_mean": ["tripod","actionable"],
              "tripod_cs_std": ["tripod","actionable"],
              "iread_is_enrolled": ["iread", "actionable"],
              "iread_data_missing": ["iread", "actionable"],
              "iread_took_screener": ["iread", "actionable"],
              "iread_average_time_per_topic": ["iread", "actionable"],
              "iread_average_sessions_per_week": ["iread", "actionable"],
              "iread_current_series": ["iread", "actionable"],
              "iread_current_topic": ["iread", "actionable"],
              "iread_screener_placement_series": ["iread", "actionable"],
              "iread_highest_unit_reached": ["iread", "actionable"],
              "iread_total_sessions": ["iread", "actionable"],
              "iread_total_topics_completed": ["iread", "actionable"],
              "iread_total_time": ["iread", "actionable"],
              "ethnicity": ["demo"],
              "ell": ["demo"],
              "ell_language": ["demo"],
              "disability_code": ["demo"],
              "service_delivery": ["demo"],
              "lunch_status": ["demo"],
              "homeless": ["demo"],
              "lives_with": ["demo"],
              "school": ["demo"],
              "age": ["demo"],
              "reenroll_num": ["reenroll"],
              "reenroll_off_peak": ["reenroll"],
              "reenroll_pss": ["reenroll"],
              "reenroll_pns": ["reenroll"],
              "reenroll_other": ["reenroll"],
              "course_taken_art": ["course"],
              "course_taken_pe": ["course"],
              "course_taken_read": ["course"],
              "course_taken_science": ["course"],
              "course_taken_math": ["course"],
              "course_taken_social": ["course"],
              "course_taken_computer": ["course"],
              "course_taken_non_grade": ["course"],
              "course_taken_language": ["course"],
              "grade_mark_a": ["grade"],
              "grade_mark_b": ["grade"],
              "grade_mark_c": ["grade"],
              "grade_mark_d": ["grade"],
              "grade_mark_f": ["grade"],
              "grade_mark_s": ["grade"],
              "grade_mark_n": ["grade"],
              "grade_mark_u": ["grade"],
              "grade_mark_e": ["grade"],
              "grade_mark_p": ["grade"],
              "grade_mark_ng": ["grade"],
              "rsa_summer_enrolled": ["summer", "actionable"],
              "discipline_num": ["discipline"],
              "discipline_disobeyed_rules": ["discipline"],
              "discipline_disrespectful_behavior": ["discipline"],
              "discipline_harassment_bullying": ["discipline"],
              "discipline_no_information": ["discipline"],
              "discipline_skipping_class": ["discipline"],
              "discipline_repeated_behavior": ["discipline"],
              "discipline_disorderly_conduct": ["discipline"],
              "discipline_sexual_misconduct": ["discipline"],
              "discipline_possess_weapon": ["discipline"],
              "discipline_stealing": ["discipline"],
              "discipline_disruptive_conduct": ["discipline"],
              "discipline_physical": ["discipline"],
              "discipline_vandalism": ["discipline"],
              "att_absence": ["attendance"],
              "att_tardiness": ["attendance"],
              "att_with_explanation": ["attendance"],
              "att_other": ["attendance"],
              "att_excused_absence": ["attendance"],
              "att_unexcused_absence": ["attendance"],
              "att_leave_early": ["attendance"],
              "att_school_activity": ["attendance"],
              "att_nurse": ["attendance"],
              "att_half_day_absence": ["attendance"],
              "att_in_school_suspension": ["attendance"],
              "att_truancy": ["attendance"],
              "att_counselor": ["attendance"],
              "att_administrator": ["attendance"],
              "tfa_summer_enrolled": ["summer", "actionable"],
              "tfa_summer_days_enrolled": ["summer", "actionable"],
              "tfa_teacher": ["summer"],
              'map_diff': ['map'],
              'map_total_diff': ['map'],
              'map_year_diff': ['map'],
              'map_std': ['map'],
              'map_num_tests': ['map'],
              'map_num_tests_term': ['map'],
              'map_num_consecutive_negs': ['map']
              }

feature_groups = defaultdict(list)
# make groups based on grouplist
for feat, group_list in group_dict.items():
    for group in group_list:
        feature_groups[group].append(feat)
        feature_groups["all"].append(feat)
